#!/usr/bin/python

import numpy as np

def fsdr(u,v):
    n = len(u)
    m = len(v)
    a = np.zeros((n,m))
    for i in range(n):
        for j in range(m):
           a[i,j] = max(1-u[i],v[j])
    return a

u = np.array([0.0, 0.1, 0.5 , 1.0 ])
v = np.array([1.0, 0.5, 0.1])
q = fsdr(u,v)
print('q =',q)
print()
